# 应用名称
spring:
  application:
    name: ziweishopcity-auth-server
# 开启模板缓存（默认值： true ）
  thymeleaf:
    cache: false
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    port: 6379
    database: 0
    host: 192.168.71.128
  session:
    store-type: redis
# 应用服务 WEB 访问端口
server:
  port: 9000
  servlet:
    session:
      timeout: 30m

