spring:
  thymeleaf:
    cache: false
  datasource:
    password: root
    username: root
    url: jdbc:mysql://192.168.71.128:3306/ziweishopcity_ums?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ziweishopcity-member
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  session:
    store-type: redis
  redis:
    port: 6379
    database: 0
    host: 192.168.71.128
mybatis-plus:
  mapper-locations:
    classpath: /mapper/**/*.xml
server:
  port: 8002