spring:
  application:
    name: ziweishopcity-third-party
  cloud:
    alicloud:
      access-key: LTAI5tRjFgDMhfM2PGx5HEYG
      secret-key: A6iFLleumPvNs7yeOY6rrwDmImWYji
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8005
