spring:
  application:
    name: ziweishopcity-coupon
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.71.128:3306/ziweishopcity_sms?serverTimezone=GMT%2B8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8006
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations:
    classpath: /mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl