spring:
  application:
    name: ziweishopcity-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.71.128
    port: 6379
    database: 0
  session:
    store-type: redis
server:
  port: 8009
  servlet:
    session:
      timeout: 30m
